language: php
php:
- '7.2'

services:
- mysql

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_script:
- composer run-script post-root-package-install
- composer run-script post-create-project-cmd
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

env:
  global:
  - DB_CONNECTION=mysql
  - DB_DATABASE=lara
  - DB_USERNAME=root
  - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS lara;'

install:
- composer self-update
- make install
- make env
- make key

after_script:
- vendor/bin/test-reporter

script:
- make test
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build -r 887cbed5268a8f6fca764aca176f81f4321cf455b39a7095cbe81f59a101dcc7 --exit-code $TRAVIS_TEST_RESULT; fi